### ISSUE TITLE
Ability to apply several migrations by name

### ISSUE THREAD

**Issue by indeyets** [mmkal/slonik-tools#188]
Migrator script takes single "2-nd" argument as a name of migration which should be enabled or disabled. It would be nice to be able to enable/disable several migrations by specifying their names on command-line.

**Comment by mmkal** [comment]
The old behaviour you've described was actually a bug. The 2nd argument (after `up`) was supposed to be the name of migration the tool should run _to_. That's now fixed, so this is a feature request now. Would an interface something like this be what you're looking for?

```
node migrate up --only migration1,migration2,migration4
```

If so, it might be necessary to make the `to` argument explicit rather than positional, to avoid confusion with `only`. i.e. `--to migration2` vs `--only migration2`, which would be a breaking change. It'll probably require using a proper cli arg parsing library too.

**Comment by mmkal** [comment]
Now supported via the `--name` arg: https://github.com/mmkal/slonik-tools/tree/master/packages/migrator#up
