### ISSUE TITLE
Support for branded types

### ISSUE THREAD

**Issue by twk** [mmkal/slonik-tools#218]
We use a lot of branded types in our codebase to make it easier to distinguish between different integers.  For example:
```
type Brand<K, T> = K & { __brand: T };
export type UserId = Brand<number, 'UserId'>;
```

It would be great to be able to indicate which columns should get which types. I saw the custom type converter for things like dates, but I didn't see any ability to do it based on the column name instead of the column type.  

Thanks!

**Comment by mmkal** [comment]
I agree, this would be useful. It might be tricky to implement in the library without complicating the API somewhat, though. And this _can_ actually be done already, albeit in a somewhat awkward way. In a single place, you can define a dictionary of `Brands`, which mark types/columns as whichever brands you like:

```typescript
type Brands = {
  CountInfo: {
    a_count: 'count'
  }
}

type Branded<T, TypeName, Field> = TypeName extends keyof Brands
  ? Field extends keyof Brands[TypeName]
    ? T & {_brand: Brands[TypeName][Field]}
    : T
  : T
```

Then instead of using `knownTypes` as-is, you can wrap the type:

```typescript
type OrigKnownTypes = typeof knownTypes

type WrappedKnownTypes = {
  [TypeName in keyof OrigKnownTypes]: {
    [Field in keyof OrigKnownTypes[TypeName]]: Branded<OrigKnownTypes[TypeName][Field], TypeName, Field>
  }
}
```

Use the modified type when setting up the type generator:

```typescript
const {sql, poolConfig} = setupTypeGen({
  reset: true,
  knownTypes: knownTypes as WrappedKnownTypes,
  writeTypes,
})
```

Then the `a_count` field of the `CountInfo` type will be branded:

```typescript
const countInfo = await slonik.one(sql.CountInfo`
  select count(*) as a_count, a as a_value
  from foo
  group by a
`)
expectTypeOf(countInfo).toEqualTypeOf<{
  a_count: number & {_brand: 'count'}
  a_value: string
}>()
```

`Brands` can be added to over time as necessary. You could also tweak `Branded` depending on your schema/conventions, e.g.

```typescript
type BrandingConventions = {
  id: 'id'
  count: 'count'
  cost: 'USD'
}

type Branded<T, TypeName, Field> = Field extends keyof BrandingConventions
  ? T & {_brand: BrandingConventions[Field]}
  : TypeName extends keyof Brands
  ? Field extends keyof Brands[TypeName]
    ? T & {_brand: Brands[TypeName][Field]}
    : T
  : T
```

If you want to get _really_ fancy, you could use [template literal types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types) to choose the brand based on field name suffix, etc.

The signature for `Branded` is complex, but you'd only have to write it once.

Let me know what you think, if this would cover your use case I may add something to the docs/tests/demo project. Working example here: https://github.com/mmkal/slonik-tools/compare/brands-example

**Comment by mmkal** [comment]
@twk curious if you ever tried this, or found another way to add brands? I like the idea, so if you have something that's working for you I'll add to the docs.

**Comment by twk** [comment]
@mmkal -- I didn't get a chance to try this. We ended up not choosing slonik for this project, but next time I start something I'll definitely try this out. I'm happy to see this is possible!

**Comment by mmkal** [comment]
The API has changed, this is now supported via [write types](https://github.com/mmkal/slonik-tools/tree/master/packages/typegen#modifying-types)
