### ISSUE TITLE
All types have nullabe properties

### ISSUE THREAD

**Issue by gajus** [mmkal/slonik-tools#357]
Don't see an open discussion about this, but all types at the moment have nullable properties, e.g.

```ts
sql<queries.Room>`
  SELECT
    r1.id,
    r1.uuid
  FROM room r1
`,
```

Produces:

```ts
export declare namespace queries {
  // Generated by @slonik/typegen

  /**
   * queries:
   * - `SELECT r1.id, r1.uuid FROM room r1`
   * - `SELECT r1.id, r1.uuid FROM room r1`
   */
  export type Room = {

    /**
     * regtype: `integer`
     */
    id: (number) | null,

    /**
     * regtype: `uuid`
     */
    uuid: (string) | null,
  };
}
```

Opening to track if there is anything we can do about it. I will dig myself into it too.

**Comment by danielrearden** [comment]
The underlying issue appears to be with `addColumnInfo` failing silently. Specifically, [the call](https://github.com/mmkal/slonik-tools/blob/master/packages/typegen/src/query/column-info.ts#L115) fails because the provided SQL includes multiple statements.

Even if you run the statements individually, though, there's still an issue in that the last statement includes a function definition that references a parameter using `$1`. This will fail because the parser reads this as a prepared statement parameter instead and expects a parameter to be passed in.

Not sure off-hand what the best workaround here is.

**Comment by mmkal** [comment]
Thanks @gajus for the report and @danielrearden for looking into it. There are limitations to the nullability checking the tool does. 

>

**Comment by danielrearden** [comment]
FWIW I'm seeing this behavior even with just a simple select from a table, no CTE, view or subquery.

**Comment by mmkal** [comment]
Could you share the slonik version you're seeing that with? Something similar happened when slonik automatically use `pg-native`: https://github.com/mmkal/slonik-tools/pull/335. I know slonik has switched to a different way of enabling/disabling pg-native since then, which is partly why slonik-tools hasn't updated to slonik v26 just yet. Might be that pg-native is being used again.

**Comment by gajus** [comment]
Just in case, Slonik dropped native driver support entirely.

**Comment by mmkal** [comment]
@gajus I think this might be a bug/regression in slonik itself. Here's a repro.

Valid SQL:

```sql
drop type if exists test_type;

create or replace function test_func(text)
returns text as
$$
declare
  input_text alias for $1;
begin

return 'input:' || input_text;

end;
$$
LANGUAGE 'plpgsql';
```

This is a simplified version of the statement that's failing with slonik v26, and was succeeding with v23. You can see it is fine in pgadmin:

![image](https://user-images.githubusercontent.com/15040698/145736749-da39ddb9-2460-4e4e-bfcc-313af2aaf570.png)

But if you run it using slonik, you get:

```
    error: cannot insert multiple commands into a prepared statement

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

slonik-typegen is hitting the same problem. Worth noting, if you make it a single statement, you just get a different error. This is what you get for the same as above but with the `drop type if exists test_type;` line:

```
    error: bind message supplies 1 parameters, but prepared statement "" requires 0

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

Could it be that slonik is getting confused by the `input_text alias for $1;` and thinks that the whole query is a prepared statement?

**Comment by gajus** [comment]
I am struggling to think of why this would have worked in any Slonik version... This behavior is very much by design.

Unfortunately, without parsing the query, it is impossible for Slonik to tell if $1 is a bound parameter reference or a function parameter reference.

For what it is worth, you can simply use named parameters:

```sql
drop type if exists test_type;

create or replace function test_func(text)
returns text as
$$
declare
  input_text alias for test_func.text;
begin

return 'input:' || input_text;

end;
$$
LANGUAGE 'plpgsql';
```

**Comment by mmkal** [comment]
I'm going to open an issue on slonik to discuss - but I don't follow the logic of this being by design. Seems like slonik is getting tripped up by _any_ `$1` that appears anywhere in the sql it's being sent. We can even see it with this much simpler repro:

```sql
select '$1'
```

I _do_ understand that it might be hard to improve in slonik, so I'm not going to close this issue as "bug in slonik", I'm going to look for a workaround.

Worth noting, for `.sql` files, slonik-typegen uses `prepare temp_statement_123 as select * from foo where bar = $1` which is another repro case of this issue. I'm not sure why it regressed between v23 and v26 but in any case, it makes more sense to discuss in the slonik repo.

**Comment by gajus** [comment]
Just confirmed that @slonik/typegen works with the latest Slonik version. 🥳
