### ISSUE TITLE
@slonik/typegen – Discussion – Upcoming feature: Ignores

### ISSUE THREAD

**Issue by janpaepke** [mmkal/slonik-tools#385]
## problem

Currently the recommended way to make slonik-typegen ignore things, is to rename the template literal.
This has several drawbacks:
1. It breaks vscode extensions like SQL Lit
2. It makes the code more verbose
3. It requires code changes which act as control symbols, which should be comments.
4. It is quite unexpected for devs unfamiliar with the pattern, which might cause accidental regressions.

## proposed solution

The current plan is to model the ignore behaviour along the syntax of eslint.

**Ignore individual queries**:
`// slonik-typegen-disable-line`
-> ignore sql in the same line

`// slonik-typegen-disable-next-line`
-> ignore sql in the next line

**Ignore file sections**:
```jsx
/* slonik-typegen-disable */
const ignoredQuery = sql`select will_be from left_untouched`
/* slonik-typegen-enable */
```

**Ignore file(s)**:
1) Ignore Option in config. (Existing)
2) `/* slonik-typegen-disable */` at top of file.

Feedback is very welcome.

**Comment by mmkal** [comment]
I think no great need for disable-line - in my opinion it’s ugly/too much cruft on one line and I suspect nobody will be too sad not to have it. If someone is sad, they can open an issue with the use case. Agreed on all the rest.

@gajus since you’ve asked for this before, any thoughts?

**Comment by janpaepke** [comment]
Another thing to consider are sql files.
How do we want to treat them?
Could you supply an example file (I don't use them)

**Comment by mmkal** [comment]
> Another thing to consider are sql files.
> How do we want to treat them?
> Could you supply an example file (I don't use them)

Easiest way to see how generation from a sql file works is in this test: https://github.com/mmkal/slonik-tools/blob/ecd6f486d645b662f403315b458b5e419f60ac38/packages/typegen/test/sql.test.ts#L31-L142

I’d suggest not doing anything for now though. 1) because it’s fairly easy to use `exclude` to ignore the whole file, 2) typegen assumes any matched files have only one query in them so inline directives just aren’t as important, 3) I suspect it’s a less used feature so we can just wait until someone requests it and explains why they don’t want to exclude at a config level (also 4. you could also fairly easily configure to look for `— typegen-ignore` in the sql file if all else fails)

One thing potentially worth considering though: an in-sql directive would automatically solve everywhere. Basically look for `—typegen-ignore` inside the sql itself, rather than in typescript. But that feels a bit weird to me, and would make single-line queries pretty cumbersome.

**Comment by janpaepke** [comment]
So I haven't started on this because I'm still weighing the options.

It's funny how our trains of thought match.
An in-sql comment was actually my first idea. I didn't propose it because as you said it makes single line queries or especially fragments "cumbersome" at best and pretty much unreadable at worst.

Yet what I also don't really like is having differing ignore logic between sql and ts files.

If that turns out to be the only option, we might want to limit ts ignores even more. Maybe only supporting section comments (as you previously suggested), so we'd have "only" 2 different ways of ignoring.

What I was also considering is this: Are queries containing "select" or "returning" the only type of queries where we'd even expect a return value?
Because if so we could ignore all others and thus solving the fragment problem even without ignores...

I'll think about this some more.

**Comment by Pimm** [comment]
Out of [all SQL commands in PSQL](https://www.postgresql.org/docs/current/sql-commands.html), I too think that `insert … returning`, `select`, `update … returning`, and `delete … returning` and the only ones relevant to this tool… except _maybe_ `values`, although I don't think this tool would be helpful with `values` anyway.

Jan, you write: "_[i]t makes the code more verbose_", which ‒ in itself ‒ is not a drawback. Could you explain why you feel verbosity is bad here? You also write "_[i]t requires code changes which act as control symbols, which should be comments_". Could you elaborate on "_which should be comments_"?

**Comment by janpaepke** [comment]
> I too think that insert … returning, select, update … returning, and delete … returning and the only ones relevant to this tool

Yeah I've tried to come up with more, and asked other people, but it seems we all agree: we can probably agree any query not including these keywords. This also means `values`, as it doesn't hurt.
This is great, as it automatically removes the need to ignore fragments, which strengthens my conviction that we probably don't need single line ignores.

> Could you elaborate on "which should be comments"?

Yes, what I mean is that the only motivation for code changes, should be changing the behaviour of the code itself, not to influence behaviour of code that processes it.  
If at all, deliberately influencing code processors should be done using comments, as they have a different task than the code itself: they store meta information about the code.

**Comment by janpaepke** [comment]
I think I share your view of typgen: It should do everything in its ability to provide types for queries.

Wether it does its magic through `gdesc` (Essentially `EXPLAIN`) or `pgsql-ast-parser` doesn't really matter, the ends justify the means. But we do accept, that it may not be able to extract every query perfectly and be vague if it's "not sure".
This can always be gradually improved later (i.e. parsing function results etc.).

My point is not every query (or fragment thereof) makes sense to be parsed. In your example I would not expect a type like `sql<{foo: number}>\`where foo = ${bar}\`` to be extracted, because if ran as is it would not return anything (or be invalid actually).

The only thing that needs to be parsed is the query using the fragment, i.e. `sql\`select * from table ${whereFragment}\``. This is where we're interested in the returning result.
Now if the columns selected are fragments as well, this is where things get tricky and I think you covered this case in the "Limitations" Section.

So it's not really about what is in principle "parsable" but where we'd expect a result. Because only there we'd want to know the types.

**Comment by mmkal** [comment]
I like it! It's a nice balance. I think it makes a lot of sense to start out with a simple regex search for the ignore pattern, and that would probably be totally fine forever. Even those edge cases you mentioned have easy workarounds. 👍 👍 👍

**Comment by mmkal** [comment]
I think we could now add some really interesting features like having the CLI fail if there are any queries it fails to add types to, since now we can ignore anything it can’t handle. This would essentially turn slonik-typegen into a sql linter too, which validates not only sql syntax but also your actual schema. It’s already doing all the hard work - watching the file system, exposing a cli, specifying the connection string, and allowing ignoring queries it can’t handle (yet). But I think that’s a separate piece of work so I’m going to close this issue. Let me know if you think it should be reopened.
