### ISSUE TITLE
Passing data to SQL

### ISSUE THREAD

**Issue by ivan-kleshnin** [mmkal/slonik-tools#45]
What if I need to pass some ENV data (like password) to the SQL migration code?

The above, I believe, is the reason most migration frameworks have JS based migrations or, at least, support `.js` in parallel to `.sql`.

**Comment by adevine** [comment]
I definitely agree with this one. Most of my tables have standard soft delete "archive" tables, so for each table I have to create an archive table, a trigger function and a BEFORE DELETE trigger, so much prefer to have that in its own function (as a sql template fragment) than copying that everywhere.

This looks like it would be very easy to do looking at https://github.com/mmkal/slonik-tools/blob/master/packages/migrator/src/index.ts#L63. I may make a go at it next weekend - would want to also support .js or .ts files (when running through ts-node), and when the files have those extensions would expect them to have a default export that is of SqlTokenType. @mmkal does that approach make sense to you?

**Comment by ivan-kleshnin** [comment]
Does this repo changed the owner? Interesting.

@adevine I switched to Knex btw. As I gradually added more and more query-builder functionality I realized it's going in that direction anyway... I don't particularly like Knex but it's objectively a more practical choice.

**Comment by mmkal** [comment]
@ivan-kleshnin it hasn't changed hands, this repo is separate from https://github.com/gajus/slonik if that's what you were thinking of.

I could definitely be open to typescript/javascript migrations. I think the usual way (at least with sequelize/umzug) is to have a file with exports named `up` and `down` rather than a default export. I'd be open to a PR doing something like that. Umzug has support for customResolvers so definitely doable.

**Comment by adevine** [comment]
Heh, @ivan-kleshnin I actually just did the opposite and switched an entire repo *over* to slonik from Knex - I pretty much agree with everything in gajus's [Stop using Knex.js](https://medium.com/@gajus/stop-using-knex-js-and-earn-30-bf410349856c) post, and with the recursive nature of sql template strings I've never been in a situation where I felt creating dynamic queries was easier in knex than slonik. Regardless of whether it's slonik or something else, I really feel that query-safe SQL template literals are a much better solution than query builder functions.

As an example, I opened [this issue](https://github.com/knex/knex/issues/3635) a while back in knex to better support identity columns in postgres. Turns out I could already do what I wanted to do, but my point is that I knew exactly the SQL I wanted to execute, but I wasted a half hour trying to hunt around trying to find the exact way to just write that statement in knex, with no safety benefit but just making things more obscured. I think probably half the open issues in knex are "Let me do this thing I know how to do in SQL in knex".

That said, I already had all my migrations written in knex, so unlike the runtime part of my codebase I don't feel any pressing need to port stuff over immediately. I do wish I had known about this project before hand, though, as I would have preferred to do it in knex.

Thanks very much @mmkal for the info, I like the standard 'up/down' exports.

**Comment by ivan-kleshnin** [comment]
@adevine so you don't write your own `select`, `update`, etc abstractions and use inline SQL everywhere?

**Comment by adevine** [comment]
@ivan-kleshnin here is one simple example of before and after of the port from knex to JS.

In knex
```
            const fieldPlaceholders = acceptableFieldValues.map(_ => '?').join(',');

            // This JSON query just ensures the user has registration_state field in one of the acceptable values
            results = await this.knex('user_registrations')
                .innerJoin('users', 'user_registrations.user_id', 'users.id')
                .where('users.xid', xid)
                .andWhereRaw(`registration_state->>? IN (${fieldPlaceholders})`, [fieldName, ...acceptableFieldValues])
                .select('users.id');
```

In slonik
```
            queryResult = await this.pool().query(sql`
                SELECT users.id
                FROM user_registrations
                JOIN users ON users.id = user_registrations.user_id
                WHERE users.xid = ${ctx.xid()}
                AND registration_state->>${fieldName} = ANY(${sql.array(acceptableFieldValues, 'text')})
            `);
```

I don't know about you, but I personally find the SQL much easier to read, especially in the part where I had to break out the "whereRaw" in knex. Pretty much everyone knows SQL, why would I want to hide it behind another layer that fewer people know? I guess my main point is that I don't find any benefit to custom `select`, `update`, etc. abstractions. They both are essentially just different ways of writing SQL, so why not just write it in the way that everyone already understands?

**Comment by adevine** [comment]
@mmkal here is a commit on my fork that should support it:

https://github.com/adevine/slonik-tools/commit/74a64f0e2e521f06ca5f2755ba050db10b10e226

I still haven't even tested this (my docker instance is borked on my machine) and it needs docs, but it was a trivial enough change.

**Comment by ivan-kleshnin** [comment]
@adevine because different parts of SQL query are often related to each other.

For example, when I need to make a join, I need to refactor my selection.

```
SELECT *
FROM post
```

becomes

```
SELECT post.*
FROM post
INNER JOIN user ON
```

And there are more couplings like that... You can't express that with a static query so it starts to wrap abstraction layers. Where conditions in my API are almost always dynamic so I have `makeWhere` at least. Same goes for filtering and sorting and aggregations.

**Comment by adevine** [comment]
@ivan-kleshnin My point is that even if I had to do that I would still much rather do that with composed templates. And while I *do* make use of composed templates, I still try to keep that to a minimum because it can obfuscate what I'm trying to do. So for your example:

```
const selectPostSql = sql`SELECT post.* FROM post`;
// then later
pool.query(sql`${selectPostSql} INNER JOIN user`);
```
And I get it, you'd say 'but what if I need to get columns from user', but this is probably not the best example because, IMO, there is rarely value in putting the select columns in a sub-template (though you could just make selectPostSql a function that took extra params). I did, however, have lots of places in my code base where I had complicated WHERE clauses in sub-templates that I reused all over the place, and IMO it ended up being easier to read that knex. In fact, in porting over my entire code base I never had an issue where what I was trying to do was easier in knex. If anything, there were quite a few cases where I had to breakout to knexRaw statements, so I was left with this mix of 'knex code' and SQL. 

Also, not really disagreeing with any of what your saying, could certainly imagine a case where things are more easily set up using a query builder, just that it took me a while to realize that 99% of what I wanted to do I could do more easily with composed templates.

Anyway, agreed, sorry mmkal for spamming the thread.

**Comment by mmkal** [comment]
@adevine - one note about the implementation in your fork. To be more consistent with [sequelize](https://sequelize.org/master/manual/migrations.html), and a little more flexible, maybe `up` and `down` could be promise-returning functions, which could have a type something like:

```typescript
import {DatabaseTransactionConnectionType, sql} from 'slonik'

export interface MigrationParams {
  slonik: DatabaseTransactionConnectionType
  sql: SqlTaggedTemplateType
}
export type Migration = (params: MigrationParams) => PromiseLike<any>
``` 

Then a migration file would look like:

```typescript
import {Migration} from '@slonik/migrator'

export const up = ({ slonik, sql }) => slonik.query(sql`create table foo(id uuid)`)
export const down = ({ slonik, sql }) => slonik.query(sql`drop table foo`)
```

The implementation would be similar, just start a transaction and pass `{ slonik: transaction, sql }` to `up` and `down` rather than calling them as queries.

Another thing to think about is whether we'd want to use ts-node, babel-node, etc. for running typescript (rather than javascript) migrations.

**Comment by mmkal** [comment]
@adevine I've published a prerelease package with this functionality, you can install with `npm install @slonik/migrator@0.3.2-migrationResolver-2020-04-06-21-32-29.3+8fc53ce`

One note: the implementation is a little different to what's discussed above. Instead of explicitly supporting typescript/javascript, you can pass in your own `migrationResolver`, which will receive an object in the form `{ path, slonik, sql }` and expects you to return an object with `up` and `down` functions: https://github.com/mmkal/slonik-tools/blob/cc8b8100afa61a1a861653f1779389abdabfff87/packages/migrator/src/index.ts#L21

You can implement that however you like - in your case you'd read the extension, and use `require(...)` if it's js, but if you wanted you could make network calls, use a different `slonik` instance, or whatever you wanted (though I wouldn't recommend anything complex).

If this works for you, I'd consider adding a predefined javascript/typescript `require` implementation to this package (or accepting one as a PR), but that would only be a convenience function. Let me know if this covers your use case.

CC @ivan-kleshnin in case you're still using slonik for migrations.

**Comment by ivan-kleshnin** [comment]
@mmkal I'm using Knex for now but I'm going to give Slonik another try. 
So thank you for the update – great job!
